version: '3'
services:

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9200 || exit 1" ]
      interval: 10s
      retries: 5
      timeout: 10s
    restart: always

#  kibana:
#    image: kibana:8.6.2
#    container_name: kibana
#    expose:
#      - "5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - XPACK_SECURITY_ENABLED=false
#    depends_on:
#      - elasticsearch
#    restart: always

  redis:
    image: redislabs/redismod:latest
    container_name: redis
    expose:
      - "6379"
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi-solution
      dockerfile: Dockerfile
    image: fastapi:latest
    container_name: fastapi
    expose:
      - "8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    image: tests:latest
    container_name: tests
    volumes:
      - ./tests:/opt/app/tests:ro
    env_file:
      - ./.env
    entrypoint: >
      sh -c "python3 functional/utils/wait_for_es.py
      && python3 functional/utils/wait_for_redis.py
      && pytest -v -W ignore::DeprecationWarning
      && tail -f /dev/null"
    depends_on:
      - fastapi

volumes:
  redis_data:
